server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: simul_tech
    password: simul_tech
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb :
      uri : mongodb://simul_tech:simul_tech@localhost:27017/ChatHistory
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

